baseURL = "https://blog.woomy.ovh"
languageCode = "fr-fr"
title = "Blog"
enableEmoji = true
theme = "PaperMod"
[params.homeInfoParams]
Title = "Plop 👋"
Content = "Bienvenue sur mon blog!"
[params]
socialIcons = [
    { name = "github", url = "https://github.com/Woomymy" },
    { name = "twitter", url = "https://twitter.com/Woomymy"},
    { name = "email", url = "mailto:github@woomy.ovh" },
    { name = "gitlab", url = "https://gitlab.com/Woomy" },
    { name = "reddit", url = "https://reddit.com/u/Woomy4680-exe" },
    { name = "telegram", url = "https://t.me/woomymy"},
    { name = "gitea", url = "https://gitea.woomy.ovh" },
    { name = "matrix", url = "https://matrix.to/#/@woomymy:matrix.org" },
    { name = "xda", url = "https://forum.xda-developers.com/m/woomymy.11816747/" }
]
ShowReadingTime = true
ShowToc = true
ShowShareButtons = true
ShowCodeCopyButtons = true
authors = ["Woomymy"]
comments = true
