baseURL = "https://woomy4680-exe.github.io/blog"
languageCode = "fr-fr"
title = "Blog"
theme = "terminal"
[params]
contentTypeName = "posts"
themeColor = "pink"
fullWidthTheme = true
CenterTheme = true